image:
- Visual Studio 2015
- Ubuntu

environment:
  PSgalleryKey:
    secure: wl8DNkBd6QUSBAEWxCNTTW+cVn32ub6kWSqZxAUrpx4/QPnWYGiLWEj+ZaFp5cuA

install:
- ps: >-

    Install-Module -Name PSScriptAnalyzer -Force  -Scope CurrentUser
    
    Install-Module -Name Pester -Force  -Scope CurrentUser
build: off
test_script:
- ps: >- 
    .\CI\CI_Start.ps1
