image:
- Visual Studio 2015
- Ubuntu

environment:
  PSgalleryKey:
    secure: wl8DNkBd6QUSBAEWxCNTTW+cVn32ub6kWSqZxAUrpx4/QPnWYGiLWEj+ZaFp5cuA

install:
- ps: >-
    .\CI\02_Install.ps1
build_script:
    .\CI\03_Build.ps1
test_script:
- ps: >-
    .\CI\04_Tests.ps1
