jobs: 
  - 
    job: Test_windows2016
    pool: 
      vmImage: vs2017-win2016
    steps: 
      - 
        displayName: "Running Tests Windows 2016"
        powershell: ".\\CI\\04_Tests.ps1\n"
      - 
        displayName: "displaing workfolder"
        powershell: "get-variable AGENT_WORKFOLDER\n"
      - 
        displayName: "displaing AGENT_BUILDDIRECTORY"
        powershell: "get-variable AGENT_BUILDDIRECTORY\n"
      - 
        displayName: "displaing BUILD_SOURCESDIRECTORY"
        powershell: "get-variable BUILD_SOURCESDIRECTORY\n"
  - 
    job: Test_Ubuntu
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - 
        displayName: "Running Tests Ubuntu"
        script: "pwsh -c .\\CI\\04_Tests.ps1"
