# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: Test_Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: .\CI\04_Tests.ps1
        displayName: 'Running Tests Ubuntu'
        
  - job: Test_windows2016
    pool:
      vmImage: 'vs2017-win2016'
      steps:
      - script: .\CI\04_Tests.ps1
        displayName: 'Running Tests Windows 2016'

